application: gae-group-project
version: 4
runtime: php55
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /style
  static_dir: style

- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /cart_update.php
  script: cart_update.php

- url: /view_cart.php
  script: view_cart.php

- url: /config.php
  script: config.php